name: biguasim
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - evdev
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.4.4=py313h06a4308_0
  - aiohttp=3.11.10=py313h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alsa-lib=1.2.13=hb9d3cd8_0
  - ansi2html=1.9.1=py313h06a4308_0
  - aom=3.9.1=hac33072_0
  - assimp=5.4.3=h8943939_0
  - attr=2.5.1=h166bdaf_1
  - attrs=24.3.0=py313h06a4308_0
  - blas=2.131=openblas
  - blas-devel=3.9.0=31_h1ea3ea9_openblas
  - blinker=1.9.0=py313h06a4308_0
  - blosc=1.21.6=he440d0b_1
  - brotli-python=1.0.9=py313h6a678d5_9
  - brotlicffi=1.0.9.2=py313h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.2=h3394656_1
  - certifi=2025.11.12=py313h06a4308_0
  - cffi=1.17.1=py313h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py313h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cuda-cccl_linux-64=12.4.127=h06a4308_2
  - cuda-cudart-dev_linux-64=12.4.127=hd681fbe_0
  - cuda-cudart-static_linux-64=12.4.127=hd681fbe_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-version=12.4=hbda6634_3
  - cupy=13.6.0=py313h586c94b_2
  - cupy-core=13.6.0=py313h28b6081_2
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dash=2.14.2=py313h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - double-conversion=3.3.1=h5888daf_0
  - embree=4.3.3=h3173236_0
  - expat=2.6.4=h6a678d5_0
  - fastrlock=0.8.3=py313h5eee18b_0
  - ffmpeg=7.1.0=gpl_h8811464_714
  - flask=3.0.3=py313h06a4308_0
  - flask-compress=1.17=py313h06a4308_0
  - fluidsynth=2.3.7=hd992666_0
  - fmt=11.0.2=h07f6e7f_1
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freeglut=3.4.0=h6a678d5_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.5.0=py313h5eee18b_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gettext=0.23.1=h5888daf_0
  - gettext-tools=0.23.1=h5888daf_0
  - gl2ps=1.4.2=hae5d5c5_1
  - glew=2.1.0=h295c915_3
  - glfw=3.4=hd590300_0
  - glib=2.82.2=h07242d1_1
  - glib-tools=2.82.2=h4833e2c_1
  - gmp=6.3.0=h6a678d5_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.24.7=h0a52356_0
  - gstreamer=1.24.7=hf3bb09a_0
  - harfbuzz=10.3.0=h76408a6_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_h2d575fe_109
  - icu=75.1=he02047a_0
  - idna=3.7=py313h06a4308_0
  - imath=3.1.12=h7955e40_0
  - importlib-metadata=8.5.0=py313h06a4308_0
  - itsdangerous=2.2.0=py313h06a4308_0
  - jack=1.9.22=h7c63dc7_2
  - jasper=4.2.4=h536e39c_0
  - jinja2=3.1.6=py313h06a4308_0
  - jsoncpp=1.9.6=hf42df4d_1
  - krb5=1.21.3=h143b758_0
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - level-zero=1.20.6=h84d6215_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.3=h6a678d5_0
  - libasprintf=0.23.1=h8e693c7_0
  - libasprintf-devel=0.23.1=h8e693c7_0
  - libass=0.17.3=hba53ac1_1
  - libavif16=1.1.1=hf3231e4_3
  - libblas=3.9.0=31_h59b9bed_openblas
  - libboost=1.86.0=h6c02f8c_3
  - libcap=2.71=h39aace5_0
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang-cpp19.1=19.1.7=default_hb5137d0_1
  - libclang13=19.1.7=default_h9c6a7e4_1
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.12.1=h332b0f4_0
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libdb=6.2.32=h6a678d5_1
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgettextpo=0.23.1=h5888daf_0
  - libgettextpo-devel=0.23.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_1
  - libglu=9.0.0=hf484d3e_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h767d61c_2
  - libgpg-error=1.51=h5eee18b_0
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - libllvm19=19.1.7=ha7bfdaf_1
  - liblzf=3.6=hb9d3cd8_3
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libmad=0.15.1b=h0b41bf4_1001
  - libmpdec=4.0.0=h5eee18b_0
  - libnetcdf=4.9.2=nompi_h00e09a9_116
  - libnghttp2=1.64.0=h161d5f1_0
  - libntlm=1.6=h7f8727e_0
  - libnvjitlink=12.4.127=h99ab3db_1
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopencv=4.11.0=qt6_py313h0134990_602
  - libopengl=1.7.0=ha4b6fd6_2
  - libopengl-devel=1.7.0=ha4b6fd6_2
  - libopenvino=2025.0.0=hdc3f47d_1
  - libopenvino-auto-batch-plugin=2025.0.0=h4d9b6c2_1
  - libopenvino-auto-plugin=2025.0.0=h4d9b6c2_1
  - libopenvino-hetero-plugin=2025.0.0=h981d57b_1
  - libopenvino-intel-cpu-plugin=2025.0.0=hdc3f47d_1
  - libopenvino-intel-gpu-plugin=2025.0.0=hdc3f47d_1
  - libopenvino-intel-npu-plugin=2025.0.0=hdc3f47d_1
  - libopenvino-ir-frontend=2025.0.0=h981d57b_1
  - libopenvino-onnx-frontend=2025.0.0=h6363af5_1
  - libopenvino-paddle-frontend=2025.0.0=h6363af5_1
  - libopenvino-pytorch-frontend=2025.0.0=h5888daf_1
  - libopenvino-tensorflow-frontend=2025.0.0=h630ec5c_1
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h5888daf_1
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.4=h27ae623_0
  - libprotobuf=5.28.3=h6128344_1
  - librsvg=2.58.4=h49af25d_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.49.1=hee588c1_1
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsystemd0=257.3=h3dc2cb9_0
  - libtheora=1.1.1=h7f8727e_3
  - libtiff=4.7.0=hd9ff511_3
  - libudev1=257.3=h9a4d06a_0
  - libunwind=1.6.2=h9c3ff4c_0
  - liburing=2.9=h84d6215_0
  - libusb=1.0.27=h520f47e_100
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h8a09558_1
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxkbcommon=1.8.0=hc4a0caf_0
  - libxml2=2.13.6=h8d12d68_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - loguru=0.7.2=py313h06a4308_1
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py313h5eee18b_0
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.1.1=py313h6a678d5_0
  - multidict=6.1.0=py313h5eee18b_0
  - mysql-common=9.0.1=h266115a_4
  - mysql-libs=9.0.1=he0572af_4
  - narwhals=1.31.0=py313h06a4308_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=py313h06a4308_0
  - nlohmann_json=3.11.2=h6a678d5_0
  - nspr=4.38=h29cc59b_0
  - nss=3.111=h159eef7_0
  - numpy-base=2.2.2=py313habf87d0_0
  - ocl-icd=2.3.2=h5eee18b_1
  - open3d=0.19.0=py313h0dccc78_0
  - openblas=0.3.29=pthreads_h6ec200e_0
  - opencv=4.11.0=qt6_py313h1de61eb_602
  - openexr=3.3.2=h6326327_1
  - openh264=2.6.0=hc22cd8d_0
  - openldap=2.6.9=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - opusfile=0.12=h3358134_2
  - packaging=24.2=py313h06a4308_0
  - pango=1.56.1=h861ebed_0
  - pcre2=10.44=hba22ea6_2
  - pip=25.0.1=pyh145f28c_0
  - pixman=0.44.2=h29eaf8c_0
  - plotly=6.0.1=py313h7040dfc_0
  - ply=3.11=pyhd8ed1ab_3
  - portaudio=19.6.0=h7b6447c_4
  - portmidi=2.0.4=h7c63dc7_2
  - proj=9.5.1=h0054346_0
  - propcache=0.3.1=py313h5eee18b_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=hb77b528_0
  - py-opencv=4.11.0=qt6_py313h0a6ee6c_602
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygame=2.6.1=py313h5fadf01_0
  - pyopengl=3.1.10=pyha804496_2
  - pyqt=5.15.10=py313h8215c10_1
  - pyqt5-sip=12.13.0=py313h46c70d0_1
  - pyqtgraph=0.14.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.2=hf636f53_101_cp313
  - python_abi=3.13=0_cp313
  - qhull=2020.2=hdb19cb5_2
  - qt-main=5.15.15=hc3cb62f_2
  - qt6-main=6.8.2=h588cce1_0
  - rav1e=0.6.6=he8a937b_2
  - readline=8.2=h5eee18b_0
  - requests=2.32.4=py313h06a4308_0
  - retrying=1.3.3=pyhd3eb1b0_2
  - sdl2=2.32.50=h9b8e6db_1
  - sdl2_image=2.8.2=h06ee604_1
  - sdl2_mixer=2.6.3=h8830914_1
  - sdl2_ttf=2.24.0=h287479f_0
  - sdl3=3.2.4=h3083f51_0
  - sip=6.8.6=py313h46c70d0_2
  - six=1.17.0=py313h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.31.1=h7b6447c_0
  - svt-av1=3.0.0=h5888daf_0
  - tbb=2022.0.0=hdb19cb5_0
  - tinyobjloader=1.0.7=h59595ed_2
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_2
  - tomli=2.3.0=pyhcf101f3_0
  - typing_extensions=4.12.2=py313h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.5.0=py313h06a4308_0
  - utfcpp=3.2.1=h06a4308_0
  - vtk-base=9.3.1=qt_py313ha954bcc_216
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.41=hd8ed1ab_0
  - werkzeug=3.0.6=py313h06a4308_0
  - wslink=2.3.4=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.11=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - yarl=1.18.0=py313h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=py313h06a4308_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py313h536fd9c_2
  - zstd=1.5.7=hb8e6e7a_1
  - pip:
      - -r requirements.txt
